defmodule JidoDelvetown.ImageGenerator.Provenance do
  @moduledoc "Safe origin data that links generated bytes to their request and provider response."

  alias JidoDelvetown.ImageGenerator.{Error, Request}

  @type t :: %__MODULE__{
          provider: String.t(),
          model: String.t(),
          adapter: String.t() | nil,
          response_id: String.t() | nil,
          prompt_sha256: String.t(),
          request_fingerprint: String.t(),
          revised_prompt: String.t() | nil,
          generated_at: DateTime.t(),
          metadata: map()
        }

  @enforce_keys [
    :provider,
    :model,
    :prompt_sha256,
    :request_fingerprint,
    :generated_at
  ]
  defstruct provider: nil,
            model: nil,
            adapter: nil,
            response_id: nil,
            prompt_sha256: nil,
            request_fingerprint: nil,
            revised_prompt: nil,
            generated_at: nil,
            metadata: %{}

  @doc "Builds provenance from the exact request and safe response identifiers."
  @spec new(Request.t(), map() | keyword()) :: {:ok, t()} | {:error, Error.t()}
  def new(request, attrs \\ %{})

  def new(%Request{} = request, attrs) when is_list(attrs) do
    if Keyword.keyword?(attrs),
      do: new(request, Map.new(attrs)),
      else: invalid(:provenance, "must be a map")
  end

  def new(%Request{} = request, attrs) when is_map(attrs) do
    with {:ok, adapter} <- optional_identifier(value(attrs, :adapter), :adapter),
         {:ok, response_id} <- optional_identifier(value(attrs, :response_id), :response_id),
         {:ok, revised_prompt} <- optional_text(value(attrs, :revised_prompt), :revised_prompt),
         {:ok, generated_at} <- generated_at(value(attrs, :generated_at, DateTime.utc_now())),
         {:ok, metadata} <- metadata(value(attrs, :metadata, %{})) do
      {:ok,
       %__MODULE__{
         provider: request.provider,
         model: request.model,
         adapter: adapter,
         response_id: response_id,
         prompt_sha256: sha256(request.prompt),
         request_fingerprint: Request.fingerprint(request),
         revised_prompt: revised_prompt,
         generated_at: DateTime.truncate(generated_at, :microsecond),
         metadata: metadata
       }}
    end
  end

  def new(%Request{}, _attrs), do: invalid(:provenance, "must be a map")

  @doc "Validates required provenance without reading provider secrets."
  @spec validate(t()) :: :ok | {:error, atom()}
  def validate(%__MODULE__{} = provenance) do
    if nonempty?(provenance.provider) and nonempty?(provenance.model) and
         optional_nonempty?(provenance.adapter) and optional_nonempty?(provenance.response_id) and
         hex_digest?(provenance.prompt_sha256) and hex_digest?(provenance.request_fingerprint) and
         optional_nonempty?(provenance.revised_prompt) and
         match?(%DateTime{}, provenance.generated_at) and
         is_map(provenance.metadata) do
      :ok
    else
      {:error, :invalid_provenance}
    end
  end

  defp optional_identifier(nil, _field), do: {:ok, nil}

  defp optional_identifier(value, field) when is_atom(value),
    do: optional_identifier(Atom.to_string(value), field)

  defp optional_identifier(value, field) when is_binary(value) do
    value = String.trim(value)
    if value == "", do: invalid(field, "must not be empty"), else: {:ok, value}
  end

  defp optional_identifier(_value, field), do: invalid(field, "must be text")

  defp optional_text(nil, _field), do: {:ok, nil}
  defp optional_text(value, _field) when is_binary(value) and value != "", do: {:ok, value}
  defp optional_text(_value, field), do: invalid(field, "must be non-empty text")

  defp generated_at(%DateTime{} = value), do: {:ok, value}
  defp generated_at(_value), do: invalid(:generated_at, "must be a DateTime")

  defp metadata(value) when is_map(value), do: {:ok, value}
  defp metadata(_value), do: invalid(:metadata, "must be a map")

  defp sha256(value) do
    value |> then(&:crypto.hash(:sha256, &1)) |> Base.encode16(case: :lower)
  end

  defp nonempty?(value), do: is_binary(value) and value != ""
  defp optional_nonempty?(nil), do: true
  defp optional_nonempty?(value), do: nonempty?(value)

  defp hex_digest?(value),
    do: is_binary(value) and byte_size(value) == 64 and value =~ ~r/\A[0-9a-f]+\z/

  defp value(attrs, key, default \\ nil) do
    case Map.fetch(attrs, key) do
      {:ok, value} -> value
      :error -> Map.get(attrs, Atom.to_string(key), default)
    end
  end

  defp invalid(field, reason) do
    {:error,
     Error.new(:invalid_response, "#{field} #{reason}", details: %{field: field, reason: reason})}
  end
end
