defmodule JidoDelvetown.ImageGenerationStagerTest do
  use ExUnit.Case, async: false

  alias JidoDelvetown.{ImageGenerationRequests, ImageGenerationStager, Repo}
  alias JidoDelvetown.ImageGenerator.{Image, Provenance, Request, Result, Usage}
  alias JidoDelvetown.ImagePostContract
  alias JidoDelvetown.Storage.{ImageArtifact, ImageDraft, ImageGenerationRequest}

  @bytes <<0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, "generated-image">>

  setup do
    clear_records()
    on_exit(&clear_records/0)
    :ok
  end

  test "stages generated bytes with provenance and completes the request" do
    request = request()
    result = result(request)
    prepare_request("portrait:v1", request)

    assert {:ok, staged} =
             ImageGenerationStager.stage(
               "portrait:v1",
               "generated:portrait:v1",
               result,
               valid_attrs()
             )

    assert staged.reused? == false
    assert staged.draft_reused? == false
    assert staged.artifact_reused? == false
    assert staged.generation_request_reused? == false
    assert staged.draft.key == "generated:portrait:v1"
    assert staged.draft.caption == valid_attrs().caption
    assert staged.draft.alt_text == valid_attrs().alt_text
    assert staged.artifact.bytes == @bytes
    assert staged.artifact.mime_type == "image/png"
    assert staged.artifact.width == 1024
    assert staged.artifact.height == 1024

    metadata = staged.artifact.source_metadata
    assert metadata["source"] == "image_generation"
    assert metadata["generation_request_id"] == "portrait:v1"
    assert metadata["provider"] == "openai"
    assert metadata["model"] == "gpt-image-1.5"
    assert metadata["adapter"] == "req_llm"
    assert metadata["provider_response_id"] == "resp_123"
    assert metadata["generated_at"] == "2026-10-06T12:00:00Z"
    assert metadata["elapsed_ms"] == 3_200
    assert metadata["usage"]["generated_images"] == 1
    assert metadata["usage"]["total_cost"] == 0.04

    assert metadata["prompt_provenance"] == %{
             "prompt_sha256" => result.provenance.prompt_sha256,
             "request_fingerprint" => result.provenance.request_fingerprint,
             "revised_prompt" => "A careful green robot"
           }

    assert staged.generation_request.state == :completed
    assert staged.generation_request.artifact_digest == staged.artifact.digest
    assert staged.generation_request.usage["total_cost"] == 0.04

    refute_received {:upload_blob, _bytes, _mime_type}
    refute_received {:create_record, _collection, _record, _rkey}
  end

  test "reuses the same durable draft, artifact, and generation receipt" do
    request = request()
    result = result(request)
    prepare_request("retry:v1", request)

    assert {:ok, first} =
             ImageGenerationStager.stage("retry:v1", "generated:retry:v1", result, valid_attrs())

    assert {:ok, second} =
             ImageGenerationStager.stage("retry:v1", "generated:retry:v1", result, valid_attrs())

    assert first.artifact.digest == second.artifact.digest
    assert second.reused?
    assert second.draft_reused?
    assert second.artifact_reused?
    assert second.generation_request_reused?
    assert Repo.aggregate(ImageGenerationRequest, :count, :request_key) == 1
    assert Repo.aggregate(ImageDraft, :count, :draft_key) == 1
    assert Repo.aggregate(ImageArtifact, :count, :digest) == 1
  end

  test "checks the durable request before it stages bytes" do
    request = request()
    prepare_request("expected:v1", request)
    different_result = result(request(prompt: "A different prompt"))

    assert {:error, :generation_request_fingerprint_mismatch} =
             ImageGenerationStager.stage(
               "expected:v1",
               "generated:wrong",
               different_result,
               valid_attrs()
             )

    assert {:error, :generation_request_not_found} =
             ImageGenerationStager.stage(
               "missing:v1",
               "generated:missing",
               result(request),
               valid_attrs()
             )

    assert Repo.aggregate(ImageDraft, :count, :draft_key) == 0
    assert Repo.aggregate(ImageArtifact, :count, :digest) == 0
    assert ImageGenerationRequests.get("expected:v1").state == :uncertain
  end

  test "requires the provider attempt to start before staging" do
    request = request()
    assert {:ok, _reservation} = ImageGenerationRequests.reserve("reserved:v1", request)

    assert {:error, {:invalid_generation_state, "reserved"}} =
             ImageGenerationStager.stage(
               "reserved:v1",
               "generated:reserved",
               result(request),
               valid_attrs()
             )

    assert Repo.aggregate(ImageDraft, :count, :draft_key) == 0
    assert Repo.aggregate(ImageArtifact, :count, :digest) == 0
  end

  test "enforces current DelveTown image and accessibility limits before completion" do
    cases = [
      {:too_large, %{bytes: :binary.copy(<<0>>, ImagePostContract.max_blob_bytes() + 1)},
       valid_attrs(), :image_too_large},
      {:unsupported_mime, %{media_type: "image/svg+xml"}, valid_attrs(), :unsupported_mime_type},
      {:invalid_dimensions, %{width: 16_385, height: 16_385}, valid_attrs(), :invalid_dimensions},
      {:missing_alt, %{}, %{valid_attrs() | alt_text: ""}, :invalid_alt_text}
    ]

    Enum.each(cases, fn {name, image_overrides, attrs, expected_error} ->
      key = "limits:#{name}"
      request = request()
      prepare_request(key, request)

      assert {:error, ^expected_error} =
               ImageGenerationStager.stage(
                 key,
                 "generated:#{name}",
                 result(request, image_overrides),
                 attrs
               )

      assert ImageGenerationRequests.get(key).state == :uncertain
    end)

    assert Repo.aggregate(ImageDraft, :count, :draft_key) == 0
    assert Repo.aggregate(ImageArtifact, :count, :digest) == 0
  end

  defp prepare_request(key, request) do
    assert {:ok, _reservation} = ImageGenerationRequests.reserve(key, request)
    assert {:ok, _started} = ImageGenerationRequests.begin_attempt(key)
  end

  defp request(overrides \\ []) do
    attrs = %{
      prompt: "AgentJido at a careful workbench",
      provider: "openai",
      model: "gpt-image-1.5",
      size: {1024, 1024},
      quality: "medium",
      output_format: :png,
      timeout_ms: 120_000,
      provider_options: %{},
      metadata: %{}
    }

    {:ok, request} = Request.new(Map.merge(attrs, Map.new(overrides)))
    request
  end

  defp result(request, image_overrides \\ %{}) do
    image_attrs =
      Map.merge(
        %{
          bytes: @bytes,
          media_type: "image/png",
          width: 1024,
          height: 1024,
          metadata: %{revised_prompt: "A careful green robot"}
        },
        image_overrides
      )

    {:ok, image} = Image.new(image_attrs)

    {:ok, usage} =
      Usage.new(
        generated_images: 1,
        input_tokens: 20,
        output_tokens: 5,
        total_tokens: 25,
        total_cost: 0.04,
        currency: "USD",
        raw: %{image_usage: %{generated: %{count: 1}}}
      )

    {:ok, provenance} =
      Provenance.new(request,
        adapter: "req_llm",
        response_id: "resp_123",
        revised_prompt: "A careful green robot",
        generated_at: ~U[2026-10-06 12:00:00Z]
      )

    {:ok, result} =
      Result.new(
        image: image,
        usage: usage,
        provenance: provenance,
        elapsed_ms: 3_200,
        provider_metadata: %{request_id: "req_123"}
      )

    result
  end

  defp valid_attrs do
    %{
      caption: "AgentJido at a careful workbench.",
      alt_text: "A green robot works at a desk."
    }
  end

  defp clear_records do
    Repo.delete_all(ImageGenerationRequest)
    Repo.delete_all(ImageDraft)
    Repo.delete_all(ImageArtifact)
  end
end
